export const pages:Record<string,{title:string,eyebrow:string,intro:string,sections:{h:string,p:string}[]}>= {
about:{eyebrow:'Who we are',title:'A school built around the child.',intro:'Laff British Montessori School is focused on helping learners grow academically, socially and personally in a safe, purposeful environment.',sections:[{h:'Our vision',p:'To nurture capable, confident and compassionate learners who are prepared to make a positive contribution to their communities.'},{h:'Our values',p:'Respect, responsibility, curiosity, integrity, excellence and kindness guide the way we teach and work with families.'}]},
'academics':{eyebrow:'Learning',title:'Strong foundations for lifelong learning.',intro:'Our academic programme builds secure foundations while encouraging curiosity, independence and critical thinking.',sections:[{h:'Early years',p:'Hands-on experiences support language, early mathematics, practical life skills, social development and discovery.'},{h:'Primary education',p:'Learners develop literacy and numeracy alongside science, technology, creative learning and wider knowledge.'},{h:'Assessment',p:'Regular assessment helps teachers understand progress and communicate learning clearly with families.'}]},
admissions:{eyebrow:'Admissions',title:'A simple path into our school.',intro:'We welcome families who share our commitment to purposeful learning and positive character development.',sections:[{h:'1. Make an enquiry',p:'Contact the school to discuss availability, age group and admission requirements.'},{h:'2. Complete the application',p:'Submit the required school application information and supporting documents through the school office.'},{h:'3. Admission decision',p:'The school reviews the application and communicates placement and onboarding information.'}]},
'principal-message':{eyebrow:"Principal's message",title:'Welcome to Laff British Montessori School.',intro:'Every child deserves to be known, encouraged and challenged to do their best.',sections:[{h:'A message to our families',p:'Our goal is to create a learning community where children feel secure enough to ask questions, brave enough to try and supported enough to grow. We look forward to partnering with families throughout that journey.'}]},
news:{eyebrow:'School news',title:'News from our learning community.',intro:'A dedicated space for school announcements, achievements and important updates.',sections:[{h:'News publishing is ready',p:'This page is structured for the administration to publish real news posts once the backend content system is connected.'}]},
events:{eyebrow:'Events',title:'What is happening at school.',intro:'Keep up with school activities, academic dates, celebrations and community events.',sections:[{h:'Events calendar',p:'The production version will connect this page to the school calendar so families can see current dates, times and event details.'}]},
gallery:{eyebrow:'Gallery',title:'A window into school life.',intro:'Photos and visual stories will showcase learning, activities, celebrations and the school environment.',sections:[{h:'Gallery management',p:'Administrators will be able to add, organize and publish approved school photographs through the connected content system.'}]},
staff:{eyebrow:'Our people',title:'Teachers who help learners thrive.',intro:'Meet the educators and support team who contribute to a caring, high-expectation learning environment.',sections:[{h:'Staff directory',p:'The production directory will contain approved staff profiles, roles and subjects after the school supplies final staff information.'}]},
contact:{eyebrow:'Contact us',title:'We would love to hear from you.',intro:'For admissions, school services or general enquiries, please use the school office contact details supplied by the administration.',sections:[{h:'School office',p:'Address: School address to be supplied. Phone: School phone to be supplied. Email: School email to be supplied.'},{h:'Enquiries',p:'The contact form can be connected to the school email or backend messaging service without exposing private credentials in the browser.'}]}
};